

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated.
// 
using System.Diagnostics.CodeAnalysis;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using GraphQL.Types;

// ReSharper disable once IdentifierTypo
namespace Contoso.Unicorn.GraphQL.Types
{
    /// <summary>
    /// Definition link input type of category.
    /// </summary>
    [SuppressMessage("ReSharper", "UnusedMember.Global")]
    [SuppressMessage("ReSharper", "MemberHidesStaticFromOuterClass")]
    [SuppressMessage("ReSharper", "InconsistentNaming")]
    [SuppressMessage("ReSharper", "PartialTypeWithSinglePart")]
    [GeneratedCode("TextTemplatingFileGenerator", "1.0.0")]
    public sealed partial class CategoryLinkInputType : InputObjectGraphType<IDictionary<string, object>>
    {
        /// <inheritdoc />
        public CategoryLinkInputType()
        {
            Name = "CategoryLinkInput";

            Description = "category link input.";

            Field(typeof(LinkArgumentInputType), "product", "Sets product link.");
        }
    }
}

// ReSharper disable once IdentifierTypo
namespace Contoso.Unicorn.GraphQL.Types
{
    /// <summary>
    /// Definition link input type of customer.
    /// </summary>
    [SuppressMessage("ReSharper", "UnusedMember.Global")]
    [SuppressMessage("ReSharper", "MemberHidesStaticFromOuterClass")]
    [SuppressMessage("ReSharper", "InconsistentNaming")]
    [SuppressMessage("ReSharper", "PartialTypeWithSinglePart")]
    [GeneratedCode("TextTemplatingFileGenerator", "1.0.0")]
    public sealed partial class CustomerLinkInputType : InputObjectGraphType<IDictionary<string, object>>
    {
        /// <inheritdoc />
        public CustomerLinkInputType()
        {
            Name = "CustomerLinkInput";

            Description = "customer link input.";

            Field(typeof(LinkArgumentInputType), "order", "Sets order link.");
        }
    }
}

// ReSharper disable once IdentifierTypo
namespace Contoso.Unicorn.GraphQL.Types
{
    /// <summary>
    /// Definition link input type of employee.
    /// </summary>
    [SuppressMessage("ReSharper", "UnusedMember.Global")]
    [SuppressMessage("ReSharper", "MemberHidesStaticFromOuterClass")]
    [SuppressMessage("ReSharper", "InconsistentNaming")]
    [SuppressMessage("ReSharper", "PartialTypeWithSinglePart")]
    [GeneratedCode("TextTemplatingFileGenerator", "1.0.0")]
    public sealed partial class EmployeeLinkInputType : InputObjectGraphType<IDictionary<string, object>>
    {
        /// <inheritdoc />
        public EmployeeLinkInputType()
        {
            Name = "EmployeeLinkInput";

            Description = "employee link input.";

            Field(typeof(LinkArgumentInputType), "employee", "Sets employee link.");

            Field(typeof(LinkArgumentInputType), "order", "Sets order link.");
        }
    }
}

// ReSharper disable once IdentifierTypo
namespace Contoso.Unicorn.GraphQL.Types
{
    /// <summary>
    /// Definition link input type of order.
    /// </summary>
    [SuppressMessage("ReSharper", "UnusedMember.Global")]
    [SuppressMessage("ReSharper", "MemberHidesStaticFromOuterClass")]
    [SuppressMessage("ReSharper", "InconsistentNaming")]
    [SuppressMessage("ReSharper", "PartialTypeWithSinglePart")]
    [GeneratedCode("TextTemplatingFileGenerator", "1.0.0")]
    public sealed partial class OrderLinkInputType : InputObjectGraphType<IDictionary<string, object>>
    {
        /// <inheritdoc />
        public OrderLinkInputType()
        {
            Name = "OrderLinkInput";

            Description = "order link input.";

            Field(typeof(LinkArgumentInputType), "customer", "Sets customer link.");

            Field(typeof(LinkArgumentInputType), "employee", "Sets employee link.");

            Field(typeof(LinkArgumentInputType), "shipper", "Sets shipper link.");

            Field(typeof(LinkArgumentInputType), "orderDetail", "Sets order detail link.");
        }
    }
}

// ReSharper disable once IdentifierTypo
namespace Contoso.Unicorn.GraphQL.Types
{
    /// <summary>
    /// Definition link input type of order detail.
    /// </summary>
    [SuppressMessage("ReSharper", "UnusedMember.Global")]
    [SuppressMessage("ReSharper", "MemberHidesStaticFromOuterClass")]
    [SuppressMessage("ReSharper", "InconsistentNaming")]
    [SuppressMessage("ReSharper", "PartialTypeWithSinglePart")]
    [GeneratedCode("TextTemplatingFileGenerator", "1.0.0")]
    public sealed partial class OrderDetailLinkInputType : InputObjectGraphType<IDictionary<string, object>>
    {
        /// <inheritdoc />
        public OrderDetailLinkInputType()
        {
            Name = "OrderDetailLinkInput";

            Description = "order detail link input.";

            Field(typeof(LinkArgumentInputType), "order", "Sets order link.");

            Field(typeof(LinkArgumentInputType), "product", "Sets product link.");
        }
    }
}

// ReSharper disable once IdentifierTypo
namespace Contoso.Unicorn.GraphQL.Types
{
    /// <summary>
    /// Definition link input type of product.
    /// </summary>
    [SuppressMessage("ReSharper", "UnusedMember.Global")]
    [SuppressMessage("ReSharper", "MemberHidesStaticFromOuterClass")]
    [SuppressMessage("ReSharper", "InconsistentNaming")]
    [SuppressMessage("ReSharper", "PartialTypeWithSinglePart")]
    [GeneratedCode("TextTemplatingFileGenerator", "1.0.0")]
    public sealed partial class ProductLinkInputType : InputObjectGraphType<IDictionary<string, object>>
    {
        /// <inheritdoc />
        public ProductLinkInputType()
        {
            Name = "ProductLinkInput";

            Description = "product link input.";

            Field(typeof(LinkArgumentInputType), "supplier", "Sets supplier link.");

            Field(typeof(LinkArgumentInputType), "category", "Sets category link.");

            Field(typeof(LinkArgumentInputType), "orderDetail", "Sets order detail link.");
        }
    }
}

// ReSharper disable once IdentifierTypo
namespace Contoso.Unicorn.GraphQL.Types
{
    /// <summary>
    /// Definition link input type of shipper.
    /// </summary>
    [SuppressMessage("ReSharper", "UnusedMember.Global")]
    [SuppressMessage("ReSharper", "MemberHidesStaticFromOuterClass")]
    [SuppressMessage("ReSharper", "InconsistentNaming")]
    [SuppressMessage("ReSharper", "PartialTypeWithSinglePart")]
    [GeneratedCode("TextTemplatingFileGenerator", "1.0.0")]
    public sealed partial class ShipperLinkInputType : InputObjectGraphType<IDictionary<string, object>>
    {
        /// <inheritdoc />
        public ShipperLinkInputType()
        {
            Name = "ShipperLinkInput";

            Description = "shipper link input.";

            Field(typeof(LinkArgumentInputType), "order", "Sets order link.");
        }
    }
}

// ReSharper disable once IdentifierTypo
namespace Contoso.Unicorn.GraphQL.Types
{
    /// <summary>
    /// Definition link input type of supplier.
    /// </summary>
    [SuppressMessage("ReSharper", "UnusedMember.Global")]
    [SuppressMessage("ReSharper", "MemberHidesStaticFromOuterClass")]
    [SuppressMessage("ReSharper", "InconsistentNaming")]
    [SuppressMessage("ReSharper", "PartialTypeWithSinglePart")]
    [GeneratedCode("TextTemplatingFileGenerator", "1.0.0")]
    public sealed partial class SupplierLinkInputType : InputObjectGraphType<IDictionary<string, object>>
    {
        /// <inheritdoc />
        public SupplierLinkInputType()
        {
            Name = "SupplierLinkInput";

            Description = "supplier link input.";

            Field(typeof(LinkArgumentInputType), "product", "Sets product link.");
        }
    }
}
