

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated.
// 
using System.Diagnostics.CodeAnalysis;
using System.CodeDom.Compiler;
using Contoso.Unicorn.GraphQL.Proxies;

// ReSharper disable once IdentifierTypo
namespace Contoso.Unicorn.GraphQL.Types
{
    /// <summary>
    /// Definition input type of category.
    /// </summary>
    [SuppressMessage("ReSharper", "UnusedMember.Global")]
    [SuppressMessage("ReSharper", "MemberHidesStaticFromOuterClass")]
    [SuppressMessage("ReSharper", "InconsistentNaming")]
    [SuppressMessage("ReSharper", "PartialTypeWithSinglePart")]
    [GeneratedCode("TextTemplatingFileGenerator", "1.0.0")]
    public partial class CategoryInputType : BaseProxyInputType<CategoryProxy>
    {
        /// <inheritdoc />
        public CategoryInputType() : base("CategoryInput")
        {
            Description = "category input.";

            Field(_ => _.CategoryName, true).Description("Sets category name");

            Field(_ => _.Description, true).Description("Sets description");
        }
    }
}

// ReSharper disable once IdentifierTypo
namespace Contoso.Unicorn.GraphQL.Types
{
    /// <summary>
    /// Definition input type of customer.
    /// </summary>
    [SuppressMessage("ReSharper", "UnusedMember.Global")]
    [SuppressMessage("ReSharper", "MemberHidesStaticFromOuterClass")]
    [SuppressMessage("ReSharper", "InconsistentNaming")]
    [SuppressMessage("ReSharper", "PartialTypeWithSinglePart")]
    [GeneratedCode("TextTemplatingFileGenerator", "1.0.0")]
    public partial class CustomerInputType : BaseProxyInputType<CustomerProxy>
    {
        /// <inheritdoc />
        public CustomerInputType() : base("CustomerInput")
        {
            Description = "customer input.";

            Field(_ => _.CompanyName, true).Description("Sets company name");

            Field(_ => _.ContactName, true).Description("Sets contact name");

            Field(_ => _.ContactTitle, true).Description("Sets contact title");

            Field(_ => _.Address, true).Description("Sets address");

            Field(_ => _.City, true).Description("Sets city");

            Field(_ => _.Region, true).Description("Sets region");

            Field(_ => _.Postalcode, true).Description("Sets postalcode");

            Field(_ => _.Country, true).Description("Sets country");

            Field(_ => _.Phone, true).Description("Sets phone");

            Field(_ => _.Fax, true).Description("Sets fax");
        }
    }
}

// ReSharper disable once IdentifierTypo
namespace Contoso.Unicorn.GraphQL.Types
{
    /// <summary>
    /// Definition input type of employee.
    /// </summary>
    [SuppressMessage("ReSharper", "UnusedMember.Global")]
    [SuppressMessage("ReSharper", "MemberHidesStaticFromOuterClass")]
    [SuppressMessage("ReSharper", "InconsistentNaming")]
    [SuppressMessage("ReSharper", "PartialTypeWithSinglePart")]
    [GeneratedCode("TextTemplatingFileGenerator", "1.0.0")]
    public partial class EmployeeInputType : BaseProxyInputType<EmployeeProxy>
    {
        /// <inheritdoc />
        public EmployeeInputType() : base("EmployeeInput")
        {
            Description = "employee input.";

            Field(_ => _.FirstName, true).Description("Sets first name");

            Field(_ => _.LastName, true).Description("Sets last name");

            Field(_ => _.Title, true).Description("Sets title");

            Field(_ => _.TitleofCourtesy, true).Description("Sets titleof courtesy");

            Field(_ => _.BirthDate, true).Description("Sets birth date");

            Field(_ => _.HireDate, true).Description("Sets hire date");

            Field(_ => _.Address, true).Description("Sets address");

            Field(_ => _.City, true).Description("Sets city");

            Field(_ => _.Region, true).Description("Sets region");

            Field(_ => _.PostalCode, true).Description("Sets postal code");

            Field(_ => _.Country, true).Description("Sets country");

            Field(_ => _.Phone, true).Description("Sets phone");

            Field(_ => _.ManagerId, true).Description("Sets manager id");
        }
    }
}

// ReSharper disable once IdentifierTypo
namespace Contoso.Unicorn.GraphQL.Types
{
    /// <summary>
    /// Definition input type of order.
    /// </summary>
    [SuppressMessage("ReSharper", "UnusedMember.Global")]
    [SuppressMessage("ReSharper", "MemberHidesStaticFromOuterClass")]
    [SuppressMessage("ReSharper", "InconsistentNaming")]
    [SuppressMessage("ReSharper", "PartialTypeWithSinglePart")]
    [GeneratedCode("TextTemplatingFileGenerator", "1.0.0")]
    public partial class OrderInputType : BaseProxyInputType<OrderProxy>
    {
        /// <inheritdoc />
        public OrderInputType() : base("OrderInput")
        {
            Description = "order input.";

            Field(_ => _.CustomerId, true).Description("Sets customer id");

            Field(_ => _.EmployeeId, true).Description("Sets employee id");

            Field(_ => _.OrderDate, true).Description("Sets order date");

            Field(_ => _.RequiredDate, true).Description("Sets required date");

            Field(_ => _.ShippedDate, true).Description("Sets shipped date");

            Field(_ => _.ShipperId, true).Description("Sets shipper id");

            Field(_ => _.Freight, true).Description("Sets freight");

            Field(_ => _.ShipName, true).Description("Sets ship name");

            Field(_ => _.ShipAddress, true).Description("Sets ship address");

            Field(_ => _.ShipCity, true).Description("Sets ship city");

            Field(_ => _.ShipRegion, true).Description("Sets ship region");

            Field(_ => _.ShipPostalCode, true).Description("Sets ship postal code");

            Field(_ => _.ShipCountry, true).Description("Sets ship country");
        }
    }
}

// ReSharper disable once IdentifierTypo
namespace Contoso.Unicorn.GraphQL.Types
{
    /// <summary>
    /// Definition input type of order detail.
    /// </summary>
    [SuppressMessage("ReSharper", "UnusedMember.Global")]
    [SuppressMessage("ReSharper", "MemberHidesStaticFromOuterClass")]
    [SuppressMessage("ReSharper", "InconsistentNaming")]
    [SuppressMessage("ReSharper", "PartialTypeWithSinglePart")]
    [GeneratedCode("TextTemplatingFileGenerator", "1.0.0")]
    public partial class OrderDetailInputType : BaseProxyInputType<OrderDetailProxy>
    {
        /// <inheritdoc />
        public OrderDetailInputType() : base("OrderDetailInput")
        {
            Description = "order detail input.";

            Field(_ => _.OrderId, true).Description("Sets order id");

            Field(_ => _.ProductId, true).Description("Sets product id");

            Field(_ => _.UnitPrice, true).Description("Sets unit price");

            Field(_ => _.Quality, true).Description("Sets quality");

            Field(_ => _.Discount, true).Description("Sets discount");
        }
    }
}

// ReSharper disable once IdentifierTypo
namespace Contoso.Unicorn.GraphQL.Types
{
    /// <summary>
    /// Definition input type of product.
    /// </summary>
    [SuppressMessage("ReSharper", "UnusedMember.Global")]
    [SuppressMessage("ReSharper", "MemberHidesStaticFromOuterClass")]
    [SuppressMessage("ReSharper", "InconsistentNaming")]
    [SuppressMessage("ReSharper", "PartialTypeWithSinglePart")]
    [GeneratedCode("TextTemplatingFileGenerator", "1.0.0")]
    public partial class ProductInputType : BaseProxyInputType<ProductProxy>
    {
        /// <inheritdoc />
        public ProductInputType() : base("ProductInput")
        {
            Description = "product input.";

            Field(_ => _.ProductName, true).Description("Sets product name");

            Field(_ => _.SupplierId, true).Description("Sets supplier id");

            Field(_ => _.CategoryId, true).Description("Sets category id");

            Field(_ => _.UnitPrice, true).Description("Sets unit price");

            Field(_ => _.IsDiscontinued, true).Description("Sets is discontinued");
        }
    }
}

// ReSharper disable once IdentifierTypo
namespace Contoso.Unicorn.GraphQL.Types
{
    /// <summary>
    /// Definition input type of shipper.
    /// </summary>
    [SuppressMessage("ReSharper", "UnusedMember.Global")]
    [SuppressMessage("ReSharper", "MemberHidesStaticFromOuterClass")]
    [SuppressMessage("ReSharper", "InconsistentNaming")]
    [SuppressMessage("ReSharper", "PartialTypeWithSinglePart")]
    [GeneratedCode("TextTemplatingFileGenerator", "1.0.0")]
    public partial class ShipperInputType : BaseProxyInputType<ShipperProxy>
    {
        /// <inheritdoc />
        public ShipperInputType() : base("ShipperInput")
        {
            Description = "shipper input.";

            Field(_ => _.CompanyName, true).Description("Sets company name");

            Field(_ => _.Phone, true).Description("Sets phone");
        }
    }
}

// ReSharper disable once IdentifierTypo
namespace Contoso.Unicorn.GraphQL.Types
{
    /// <summary>
    /// Definition input type of supplier.
    /// </summary>
    [SuppressMessage("ReSharper", "UnusedMember.Global")]
    [SuppressMessage("ReSharper", "MemberHidesStaticFromOuterClass")]
    [SuppressMessage("ReSharper", "InconsistentNaming")]
    [SuppressMessage("ReSharper", "PartialTypeWithSinglePart")]
    [GeneratedCode("TextTemplatingFileGenerator", "1.0.0")]
    public partial class SupplierInputType : BaseProxyInputType<SupplierProxy>
    {
        /// <inheritdoc />
        public SupplierInputType() : base("SupplierInput")
        {
            Description = "supplier input.";

            Field(_ => _.CompanyName, true).Description("Sets company name");

            Field(_ => _.ContactName, true).Description("Sets contact name");

            Field(_ => _.ContactTitle, true).Description("Sets contact title");

            Field(_ => _.Address, true).Description("Sets address");

            Field(_ => _.City, true).Description("Sets city");

            Field(_ => _.Region, true).Description("Sets region");

            Field(_ => _.PostalCode, true).Description("Sets postal code");

            Field(_ => _.Country, true).Description("Sets country");

            Field(_ => _.Phone, true).Description("Sets phone");

            Field(_ => _.Fax, true).Description("Sets fax");
        }
    }
}
