

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated.
// 
using System.Diagnostics.CodeAnalysis;
using System.CodeDom.Compiler;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

// ReSharper disable once IdentifierTypo
namespace Contoso.Unicorn.Entities
{
    /// <summary>
    /// Definition of table category.
    /// </summary>
    [SuppressMessage("ReSharper", "UnusedMember.Global")]
    [SuppressMessage("ReSharper", "MemberHidesStaticFromOuterClass")]
    [SuppressMessage("ReSharper", "InconsistentNaming")]
    [SuppressMessage("ReSharper", "PartialTypeWithSinglePart")]
    [GeneratedCode("TextTemplatingFileGenerator", "1.0.0")]
    [Table("Category", Schema = "dbo")]
    public partial class CategoryEntity : BaseEntity
    {
        /// <summary>
        /// Gets or sets value from column [CategoryName].
        /// </summary>
        [Required]
        [StringLength(30)]
        public virtual System.String CategoryName { get; set; }

        /// <summary>
        /// Gets or sets value from column [Description].
        /// </summary>
        [Required]
        [StringLength(400)]
        public virtual System.String Description { get; set; }
    }
}

// ReSharper disable once IdentifierTypo
namespace Contoso.Unicorn.Entities
{
    /// <summary>
    /// Definition of table customer.
    /// </summary>
    [SuppressMessage("ReSharper", "UnusedMember.Global")]
    [SuppressMessage("ReSharper", "MemberHidesStaticFromOuterClass")]
    [SuppressMessage("ReSharper", "InconsistentNaming")]
    [SuppressMessage("ReSharper", "PartialTypeWithSinglePart")]
    [GeneratedCode("TextTemplatingFileGenerator", "1.0.0")]
    [Table("Customer", Schema = "dbo")]
    public partial class CustomerEntity : BaseEntity
    {
        /// <summary>
        /// Gets or sets value from column [CompanyName].
        /// </summary>
        [Required]
        [StringLength(80)]
        public virtual System.String CompanyName { get; set; }

        /// <summary>
        /// Gets or sets value from column [ContactName].
        /// </summary>
        [Required]
        [StringLength(60)]
        public virtual System.String ContactName { get; set; }

        /// <summary>
        /// Gets or sets value from column [ContactTitle].
        /// </summary>
        [Required]
        [StringLength(60)]
        public virtual System.String ContactTitle { get; set; }

        /// <summary>
        /// Gets or sets value from column [Address].
        /// </summary>
        [Required]
        [StringLength(120)]
        public virtual System.String Address { get; set; }

        /// <summary>
        /// Gets or sets value from column [City].
        /// </summary>
        [Required]
        [StringLength(30)]
        public virtual System.String City { get; set; }

        /// <summary>
        /// Gets or sets value from column [Region].
        /// </summary>
        [StringLength(30)]
        public virtual System.String Region { get; set; }

        /// <summary>
        /// Gets or sets value from column [Postalcode].
        /// </summary>
        [StringLength(20)]
        public virtual System.String Postalcode { get; set; }

        /// <summary>
        /// Gets or sets value from column [Country].
        /// </summary>
        [Required]
        [StringLength(30)]
        public virtual System.String Country { get; set; }

        /// <summary>
        /// Gets or sets value from column [Phone].
        /// </summary>
        [Required]
        [StringLength(48)]
        public virtual System.String Phone { get; set; }

        /// <summary>
        /// Gets or sets value from column [Fax].
        /// </summary>
        [StringLength(48)]
        public virtual System.String Fax { get; set; }
    }
}

// ReSharper disable once IdentifierTypo
namespace Contoso.Unicorn.Entities
{
    /// <summary>
    /// Definition of table employee.
    /// </summary>
    [SuppressMessage("ReSharper", "UnusedMember.Global")]
    [SuppressMessage("ReSharper", "MemberHidesStaticFromOuterClass")]
    [SuppressMessage("ReSharper", "InconsistentNaming")]
    [SuppressMessage("ReSharper", "PartialTypeWithSinglePart")]
    [GeneratedCode("TextTemplatingFileGenerator", "1.0.0")]
    [Table("Employee", Schema = "dbo")]
    public partial class EmployeeEntity : BaseEntity
    {
        /// <summary>
        /// Gets or sets value from column [FirstName].
        /// </summary>
        [Required]
        [StringLength(510)]
        public virtual System.String FirstName { get; set; }

        /// <summary>
        /// Gets or sets value from column [LastName].
        /// </summary>
        [Required]
        [StringLength(510)]
        public virtual System.String LastName { get; set; }

        /// <summary>
        /// Gets or sets value from column [Title].
        /// </summary>
        [Required]
        [StringLength(60)]
        public virtual System.String Title { get; set; }

        /// <summary>
        /// Gets or sets value from column [TitleofCourtesy].
        /// </summary>
        [Required]
        [StringLength(25)]
        public virtual System.String TitleofCourtesy { get; set; }

        /// <summary>
        /// Gets or sets value from column [BirthDate].
        /// </summary>
        [Required]
        public virtual System.DateTime BirthDate { get; set; }

        /// <summary>
        /// Gets or sets value from column [HireDate].
        /// </summary>
        [Required]
        public virtual System.DateTime HireDate { get; set; }

        /// <summary>
        /// Gets or sets value from column [Address].
        /// </summary>
        [Required]
        [StringLength(120)]
        public virtual System.String Address { get; set; }

        /// <summary>
        /// Gets or sets value from column [City].
        /// </summary>
        [Required]
        [StringLength(30)]
        public virtual System.String City { get; set; }

        /// <summary>
        /// Gets or sets value from column [Region].
        /// </summary>
        [StringLength(30)]
        public virtual System.String Region { get; set; }

        /// <summary>
        /// Gets or sets value from column [PostalCode].
        /// </summary>
        [StringLength(20)]
        public virtual System.String PostalCode { get; set; }

        /// <summary>
        /// Gets or sets value from column [Country].
        /// </summary>
        [Required]
        [StringLength(30)]
        public virtual System.String Country { get; set; }

        /// <summary>
        /// Gets or sets value from column [Phone].
        /// </summary>
        [Required]
        [StringLength(48)]
        public virtual System.String Phone { get; set; }

        /// <summary>
        /// Gets or sets value from column [ManagerId].
        /// </summary>
        [StringLength(36)]
        public virtual System.String ManagerId { get; set; }
    }
}

// ReSharper disable once IdentifierTypo
namespace Contoso.Unicorn.Entities
{
    /// <summary>
    /// Definition of table order.
    /// </summary>
    [SuppressMessage("ReSharper", "UnusedMember.Global")]
    [SuppressMessage("ReSharper", "MemberHidesStaticFromOuterClass")]
    [SuppressMessage("ReSharper", "InconsistentNaming")]
    [SuppressMessage("ReSharper", "PartialTypeWithSinglePart")]
    [GeneratedCode("TextTemplatingFileGenerator", "1.0.0")]
    [Table("Order", Schema = "dbo")]
    public partial class OrderEntity : BaseEntity
    {
        /// <summary>
        /// Gets or sets value from column [CustomerId].
        /// </summary>
        [StringLength(36)]
        public virtual System.String CustomerId { get; set; }

        /// <summary>
        /// Gets or sets value from column [EmployeeId].
        /// </summary>
        [Required]
        [StringLength(36)]
        public virtual System.String EmployeeId { get; set; }

        /// <summary>
        /// Gets or sets value from column [OrderDate].
        /// </summary>
        [Required]
        public virtual System.DateTime OrderDate { get; set; }

        /// <summary>
        /// Gets or sets value from column [RequiredDate].
        /// </summary>
        [Required]
        public virtual System.DateTime RequiredDate { get; set; }

        /// <summary>
        /// Gets or sets value from column [ShippedDate].
        /// </summary>
        public virtual System.DateTime? ShippedDate { get; set; }

        /// <summary>
        /// Gets or sets value from column [ShipperId].
        /// </summary>
        [Required]
        [StringLength(36)]
        public virtual System.String ShipperId { get; set; }

        /// <summary>
        /// Gets or sets value from column [Freight].
        /// </summary>
        [Required]
        public virtual System.Decimal Freight { get; set; }

        /// <summary>
        /// Gets or sets value from column [ShipName].
        /// </summary>
        [Required]
        [StringLength(40)]
        public virtual System.String ShipName { get; set; }

        /// <summary>
        /// Gets or sets value from column [ShipAddress].
        /// </summary>
        [Required]
        [StringLength(60)]
        public virtual System.String ShipAddress { get; set; }

        /// <summary>
        /// Gets or sets value from column [ShipCity].
        /// </summary>
        [Required]
        [StringLength(15)]
        public virtual System.String ShipCity { get; set; }

        /// <summary>
        /// Gets or sets value from column [ShipRegion].
        /// </summary>
        [StringLength(15)]
        public virtual System.String ShipRegion { get; set; }

        /// <summary>
        /// Gets or sets value from column [ShipPostalCode].
        /// </summary>
        [StringLength(10)]
        public virtual System.String ShipPostalCode { get; set; }

        /// <summary>
        /// Gets or sets value from column [ShipCountry].
        /// </summary>
        [Required]
        [StringLength(15)]
        public virtual System.String ShipCountry { get; set; }
    }
}

// ReSharper disable once IdentifierTypo
namespace Contoso.Unicorn.Entities
{
    /// <summary>
    /// Definition of table order detail.
    /// </summary>
    [SuppressMessage("ReSharper", "UnusedMember.Global")]
    [SuppressMessage("ReSharper", "MemberHidesStaticFromOuterClass")]
    [SuppressMessage("ReSharper", "InconsistentNaming")]
    [SuppressMessage("ReSharper", "PartialTypeWithSinglePart")]
    [GeneratedCode("TextTemplatingFileGenerator", "1.0.0")]
    [Table("OrderDetail", Schema = "dbo")]
    public partial class OrderDetailEntity : BaseEntity
    {
        /// <summary>
        /// Gets or sets value from column [OrderId].
        /// </summary>
        [Required]
        [StringLength(36)]
        public virtual System.String OrderId { get; set; }

        /// <summary>
        /// Gets or sets value from column [ProductId].
        /// </summary>
        [Required]
        [StringLength(36)]
        public virtual System.String ProductId { get; set; }

        /// <summary>
        /// Gets or sets value from column [UnitPrice].
        /// </summary>
        [Required]
        public virtual System.Decimal UnitPrice { get; set; }

        /// <summary>
        /// Gets or sets value from column [Quality].
        /// </summary>
        [Required]
        public virtual System.Int16 Quality { get; set; }

        /// <summary>
        /// Gets or sets value from column [Discount].
        /// </summary>
        [Required]
        public virtual System.Decimal Discount { get; set; }
    }
}

// ReSharper disable once IdentifierTypo
namespace Contoso.Unicorn.Entities
{
    /// <summary>
    /// Definition of table product.
    /// </summary>
    [SuppressMessage("ReSharper", "UnusedMember.Global")]
    [SuppressMessage("ReSharper", "MemberHidesStaticFromOuterClass")]
    [SuppressMessage("ReSharper", "InconsistentNaming")]
    [SuppressMessage("ReSharper", "PartialTypeWithSinglePart")]
    [GeneratedCode("TextTemplatingFileGenerator", "1.0.0")]
    [Table("Product", Schema = "dbo")]
    public partial class ProductEntity : BaseEntity
    {
        /// <summary>
        /// Gets or sets value from column [ProductName].
        /// </summary>
        [Required]
        [StringLength(40)]
        public virtual System.String ProductName { get; set; }

        /// <summary>
        /// Gets or sets value from column [SupplierId].
        /// </summary>
        [Required]
        [StringLength(36)]
        public virtual System.String SupplierId { get; set; }

        /// <summary>
        /// Gets or sets value from column [CategoryId].
        /// </summary>
        [Required]
        [StringLength(36)]
        public virtual System.String CategoryId { get; set; }

        /// <summary>
        /// Gets or sets value from column [UnitPrice].
        /// </summary>
        [Required]
        public virtual System.Decimal UnitPrice { get; set; }

        /// <summary>
        /// Gets or sets value from column [IsDiscontinued].
        /// </summary>
        [Required]
        public virtual System.Boolean IsDiscontinued { get; set; }
    }
}

// ReSharper disable once IdentifierTypo
namespace Contoso.Unicorn.Entities
{
    /// <summary>
    /// Definition of table shipper.
    /// </summary>
    [SuppressMessage("ReSharper", "UnusedMember.Global")]
    [SuppressMessage("ReSharper", "MemberHidesStaticFromOuterClass")]
    [SuppressMessage("ReSharper", "InconsistentNaming")]
    [SuppressMessage("ReSharper", "PartialTypeWithSinglePart")]
    [GeneratedCode("TextTemplatingFileGenerator", "1.0.0")]
    [Table("Shipper", Schema = "dbo")]
    public partial class ShipperEntity : BaseEntity
    {
        /// <summary>
        /// Gets or sets value from column [CompanyName].
        /// </summary>
        [Required]
        [StringLength(80)]
        public virtual System.String CompanyName { get; set; }

        /// <summary>
        /// Gets or sets value from column [Phone].
        /// </summary>
        [Required]
        [StringLength(60)]
        public virtual System.String Phone { get; set; }
    }
}

// ReSharper disable once IdentifierTypo
namespace Contoso.Unicorn.Entities
{
    /// <summary>
    /// Definition of table supplier.
    /// </summary>
    [SuppressMessage("ReSharper", "UnusedMember.Global")]
    [SuppressMessage("ReSharper", "MemberHidesStaticFromOuterClass")]
    [SuppressMessage("ReSharper", "InconsistentNaming")]
    [SuppressMessage("ReSharper", "PartialTypeWithSinglePart")]
    [GeneratedCode("TextTemplatingFileGenerator", "1.0.0")]
    [Table("Supplier", Schema = "dbo")]
    public partial class SupplierEntity : BaseEntity
    {
        /// <summary>
        /// Gets or sets value from column [CompanyName].
        /// </summary>
        [Required]
        [StringLength(80)]
        public virtual System.String CompanyName { get; set; }

        /// <summary>
        /// Gets or sets value from column [ContactName].
        /// </summary>
        [Required]
        [StringLength(60)]
        public virtual System.String ContactName { get; set; }

        /// <summary>
        /// Gets or sets value from column [ContactTitle].
        /// </summary>
        [Required]
        [StringLength(60)]
        public virtual System.String ContactTitle { get; set; }

        /// <summary>
        /// Gets or sets value from column [Address].
        /// </summary>
        [Required]
        [StringLength(120)]
        public virtual System.String Address { get; set; }

        /// <summary>
        /// Gets or sets value from column [City].
        /// </summary>
        [Required]
        [StringLength(30)]
        public virtual System.String City { get; set; }

        /// <summary>
        /// Gets or sets value from column [Region].
        /// </summary>
        [StringLength(30)]
        public virtual System.String Region { get; set; }

        /// <summary>
        /// Gets or sets value from column [PostalCode].
        /// </summary>
        [StringLength(20)]
        public virtual System.String PostalCode { get; set; }

        /// <summary>
        /// Gets or sets value from column [Country].
        /// </summary>
        [Required]
        [StringLength(30)]
        public virtual System.String Country { get; set; }

        /// <summary>
        /// Gets or sets value from column [Phone].
        /// </summary>
        [Required]
        [StringLength(48)]
        public virtual System.String Phone { get; set; }

        /// <summary>
        /// Gets or sets value from column [Fax].
        /// </summary>
        [StringLength(48)]
        public virtual System.String Fax { get; set; }
    }
}
