

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated.
// 
using System;
using System.Diagnostics.CodeAnalysis;
using System.CodeDom.Compiler;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Reflection;
using Contoso.Unicorn.Entities;

// ReSharper disable once IdentifierTypo
namespace Contoso.Unicorn.GraphQL.Proxies
{
    /// <summary>
    /// Definition of table BaseProxy.
    /// </summary>
    [SuppressMessage("ReSharper", "UnusedMember.Global")]
    [SuppressMessage("ReSharper", "MemberHidesStaticFromOuterClass")]
    [SuppressMessage("ReSharper", "InconsistentNaming")]
    [SuppressMessage("ReSharper", "PartialTypeWithSinglePart")]
    public class AbstractProxy
    {
        private readonly IDictionary<string, object> _dictionary =
            new ConcurrentDictionary<string, object>(System.StringComparer.InvariantCultureIgnoreCase);

        /// <summary>
        /// Gets or sets value base index.
        /// </summary>
        /// <param name="index"></param>
        /// <returns></returns>
        public object this[string index]
        {
            get
            {
                var temp = GetType().GetProperty(index,
                    BindingFlags.GetProperty | BindingFlags.Public | BindingFlags.Instance | BindingFlags.IgnoreCase);
                return temp != null ? temp.GetValue(this) : _dictionary[index];
            }
            set
            {
                var temp = GetType().GetProperty(index,
                    BindingFlags.SetProperty | BindingFlags.Public | BindingFlags.Instance | BindingFlags.IgnoreCase);
                if (temp != null) temp.SetValue(this, value);
                else _dictionary[index] = value;
            }
        }
    }

    /// <summary>
    /// Definition of table BaseProxy.
    /// </summary>
    [SuppressMessage("ReSharper", "UnusedMember.Global")]
    [SuppressMessage("ReSharper", "MemberHidesStaticFromOuterClass")]
    [SuppressMessage("ReSharper", "InconsistentNaming")]
    [SuppressMessage("ReSharper", "PartialTypeWithSinglePart")]
    public partial class BaseProxy : AbstractProxy, IEquatable<BaseProxy>
    {
        /// <summary>
        /// Construct base proxy.
        /// </summary>
        /// <param name="entity">Entity.</param>
        public BaseProxy(BaseEntity entity) => Entity = entity;

        /// <summary>
        /// Gets entity.
        /// </summary>
        public BaseEntity Entity { get; }

        /// <summary>
        /// Gets or sets id.
        /// </summary>
        public virtual string Id
        {
            get => Entity.Id;
            set => Entity.Id = value;
        }

        /// <summary>
        /// Gets or sets created date.
        /// </summary>
        public virtual System.DateTimeOffset CreatedDate
        {
            get => Entity.CreatedDate;
            set => Entity.CreatedDate = value;
        }

        /// <summary>
        /// Gets or sets modified date.
        /// </summary>
        public virtual System.DateTimeOffset? ModifiedDate
        {
            get => Entity.ModifiedDate;
            set => Entity.ModifiedDate = value;
        }

        /// <summary>
        /// Gets or sets deleted date.
        /// </summary>
        public virtual System.DateTimeOffset? DeletedDate
        {
            get => Entity.DeletedDate;
            set => Entity.DeletedDate = value;
        }

        /// <summary>
        /// Gets or sets state.
        /// </summary>
        public virtual string State
        {
            get => Entity.State;
            set => Entity.State = value;
        }

        /// <summary>
        /// Gets or sets base.
        /// </summary>
        public virtual BaseProxy Base { get; set; }

        /// <inheritdoc />
        public bool Equals(BaseProxy other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;
            return Id.Equals(other.Id);
        }

        /// <inheritdoc />
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            if (obj.GetType() != this.GetType()) return false;
            return Equals((BaseProxy) obj);
        }

        /// <inheritdoc />
        public override int GetHashCode() => Entity.GetHashCode();
    }
}

// ReSharper disable once IdentifierTypo
namespace Contoso.Unicorn.GraphQL.Proxies
{
    /// <summary>
    /// Definition of table category.
    /// </summary>
    [SuppressMessage("ReSharper", "UnusedMember.Global")]
    [SuppressMessage("ReSharper", "MemberHidesStaticFromOuterClass")]
    [SuppressMessage("ReSharper", "InconsistentNaming")]
    [SuppressMessage("ReSharper", "PartialTypeWithSinglePart")]
    [GeneratedCode("TextTemplatingFileGenerator", "1.0.0")]
    public partial class CategoryProxy : BaseProxy
    {
        private readonly CategoryEntity _entity;

        /// <inheritdoc />
        public CategoryProxy(CategoryEntity entity) : base(entity) => _entity = entity;

        /// <summary>
        /// Gets or sets value from column [CategoryName].
        /// </summary>
        public virtual System.String CategoryName
        {
            get => _entity.CategoryName;
            set => _entity.CategoryName = value;
        }

        /// <summary>
        /// Gets or sets value from column [Description].
        /// </summary>
        public virtual System.String Description
        {
            get => _entity.Description;
            set => _entity.Description = value;
        }
    }
}

// ReSharper disable once IdentifierTypo
namespace Contoso.Unicorn.GraphQL.Proxies
{
    /// <summary>
    /// Definition of table customer.
    /// </summary>
    [SuppressMessage("ReSharper", "UnusedMember.Global")]
    [SuppressMessage("ReSharper", "MemberHidesStaticFromOuterClass")]
    [SuppressMessage("ReSharper", "InconsistentNaming")]
    [SuppressMessage("ReSharper", "PartialTypeWithSinglePart")]
    [GeneratedCode("TextTemplatingFileGenerator", "1.0.0")]
    public partial class CustomerProxy : BaseProxy
    {
        private readonly CustomerEntity _entity;

        /// <inheritdoc />
        public CustomerProxy(CustomerEntity entity) : base(entity) => _entity = entity;

        /// <summary>
        /// Gets or sets value from column [CompanyName].
        /// </summary>
        public virtual System.String CompanyName
        {
            get => _entity.CompanyName;
            set => _entity.CompanyName = value;
        }

        /// <summary>
        /// Gets or sets value from column [ContactName].
        /// </summary>
        public virtual System.String ContactName
        {
            get => _entity.ContactName;
            set => _entity.ContactName = value;
        }

        /// <summary>
        /// Gets or sets value from column [ContactTitle].
        /// </summary>
        public virtual System.String ContactTitle
        {
            get => _entity.ContactTitle;
            set => _entity.ContactTitle = value;
        }

        /// <summary>
        /// Gets or sets value from column [Address].
        /// </summary>
        public virtual System.String Address
        {
            get => _entity.Address;
            set => _entity.Address = value;
        }

        /// <summary>
        /// Gets or sets value from column [City].
        /// </summary>
        public virtual System.String City
        {
            get => _entity.City;
            set => _entity.City = value;
        }

        /// <summary>
        /// Gets or sets value from column [Region].
        /// </summary>
        public virtual System.String Region
        {
            get => _entity.Region;
            set => _entity.Region = value;
        }

        /// <summary>
        /// Gets or sets value from column [Postalcode].
        /// </summary>
        public virtual System.String Postalcode
        {
            get => _entity.Postalcode;
            set => _entity.Postalcode = value;
        }

        /// <summary>
        /// Gets or sets value from column [Country].
        /// </summary>
        public virtual System.String Country
        {
            get => _entity.Country;
            set => _entity.Country = value;
        }

        /// <summary>
        /// Gets or sets value from column [Phone].
        /// </summary>
        public virtual System.String Phone
        {
            get => _entity.Phone;
            set => _entity.Phone = value;
        }

        /// <summary>
        /// Gets or sets value from column [Fax].
        /// </summary>
        public virtual System.String Fax
        {
            get => _entity.Fax;
            set => _entity.Fax = value;
        }
    }
}

// ReSharper disable once IdentifierTypo
namespace Contoso.Unicorn.GraphQL.Proxies
{
    /// <summary>
    /// Definition of table employee.
    /// </summary>
    [SuppressMessage("ReSharper", "UnusedMember.Global")]
    [SuppressMessage("ReSharper", "MemberHidesStaticFromOuterClass")]
    [SuppressMessage("ReSharper", "InconsistentNaming")]
    [SuppressMessage("ReSharper", "PartialTypeWithSinglePart")]
    [GeneratedCode("TextTemplatingFileGenerator", "1.0.0")]
    public partial class EmployeeProxy : BaseProxy
    {
        private readonly EmployeeEntity _entity;

        /// <inheritdoc />
        public EmployeeProxy(EmployeeEntity entity) : base(entity) => _entity = entity;

        /// <summary>
        /// Gets or sets value from column [FirstName].
        /// </summary>
        public virtual System.String FirstName
        {
            get => _entity.FirstName;
            set => _entity.FirstName = value;
        }

        /// <summary>
        /// Gets or sets value from column [LastName].
        /// </summary>
        public virtual System.String LastName
        {
            get => _entity.LastName;
            set => _entity.LastName = value;
        }

        /// <summary>
        /// Gets or sets value from column [Title].
        /// </summary>
        public virtual System.String Title
        {
            get => _entity.Title;
            set => _entity.Title = value;
        }

        /// <summary>
        /// Gets or sets value from column [TitleofCourtesy].
        /// </summary>
        public virtual System.String TitleofCourtesy
        {
            get => _entity.TitleofCourtesy;
            set => _entity.TitleofCourtesy = value;
        }

        /// <summary>
        /// Gets or sets value from column [BirthDate].
        /// </summary>
        public virtual System.DateTime BirthDate
        {
            get => _entity.BirthDate;
            set => _entity.BirthDate = value;
        }

        /// <summary>
        /// Gets or sets value from column [HireDate].
        /// </summary>
        public virtual System.DateTime HireDate
        {
            get => _entity.HireDate;
            set => _entity.HireDate = value;
        }

        /// <summary>
        /// Gets or sets value from column [Address].
        /// </summary>
        public virtual System.String Address
        {
            get => _entity.Address;
            set => _entity.Address = value;
        }

        /// <summary>
        /// Gets or sets value from column [City].
        /// </summary>
        public virtual System.String City
        {
            get => _entity.City;
            set => _entity.City = value;
        }

        /// <summary>
        /// Gets or sets value from column [Region].
        /// </summary>
        public virtual System.String Region
        {
            get => _entity.Region;
            set => _entity.Region = value;
        }

        /// <summary>
        /// Gets or sets value from column [PostalCode].
        /// </summary>
        public virtual System.String PostalCode
        {
            get => _entity.PostalCode;
            set => _entity.PostalCode = value;
        }

        /// <summary>
        /// Gets or sets value from column [Country].
        /// </summary>
        public virtual System.String Country
        {
            get => _entity.Country;
            set => _entity.Country = value;
        }

        /// <summary>
        /// Gets or sets value from column [Phone].
        /// </summary>
        public virtual System.String Phone
        {
            get => _entity.Phone;
            set => _entity.Phone = value;
        }

        /// <summary>
        /// Gets or sets value from column [ManagerId].
        /// </summary>
        public virtual System.String ManagerId
        {
            get => _entity.ManagerId;
            set => _entity.ManagerId = value;
        }
    }
}

// ReSharper disable once IdentifierTypo
namespace Contoso.Unicorn.GraphQL.Proxies
{
    /// <summary>
    /// Definition of table order.
    /// </summary>
    [SuppressMessage("ReSharper", "UnusedMember.Global")]
    [SuppressMessage("ReSharper", "MemberHidesStaticFromOuterClass")]
    [SuppressMessage("ReSharper", "InconsistentNaming")]
    [SuppressMessage("ReSharper", "PartialTypeWithSinglePart")]
    [GeneratedCode("TextTemplatingFileGenerator", "1.0.0")]
    public partial class OrderProxy : BaseProxy
    {
        private readonly OrderEntity _entity;

        /// <inheritdoc />
        public OrderProxy(OrderEntity entity) : base(entity) => _entity = entity;

        /// <summary>
        /// Gets or sets value from column [CustomerId].
        /// </summary>
        public virtual System.String CustomerId
        {
            get => _entity.CustomerId;
            set => _entity.CustomerId = value;
        }

        /// <summary>
        /// Gets or sets value from column [EmployeeId].
        /// </summary>
        public virtual System.String EmployeeId
        {
            get => _entity.EmployeeId;
            set => _entity.EmployeeId = value;
        }

        /// <summary>
        /// Gets or sets value from column [OrderDate].
        /// </summary>
        public virtual System.DateTime OrderDate
        {
            get => _entity.OrderDate;
            set => _entity.OrderDate = value;
        }

        /// <summary>
        /// Gets or sets value from column [RequiredDate].
        /// </summary>
        public virtual System.DateTime RequiredDate
        {
            get => _entity.RequiredDate;
            set => _entity.RequiredDate = value;
        }

        /// <summary>
        /// Gets or sets value from column [ShippedDate].
        /// </summary>
        public virtual System.DateTime? ShippedDate
        {
            get => _entity.ShippedDate;
            set => _entity.ShippedDate = value;
        }

        /// <summary>
        /// Gets or sets value from column [ShipperId].
        /// </summary>
        public virtual System.String ShipperId
        {
            get => _entity.ShipperId;
            set => _entity.ShipperId = value;
        }

        /// <summary>
        /// Gets or sets value from column [Freight].
        /// </summary>
        public virtual System.Decimal Freight
        {
            get => _entity.Freight;
            set => _entity.Freight = value;
        }

        /// <summary>
        /// Gets or sets value from column [ShipName].
        /// </summary>
        public virtual System.String ShipName
        {
            get => _entity.ShipName;
            set => _entity.ShipName = value;
        }

        /// <summary>
        /// Gets or sets value from column [ShipAddress].
        /// </summary>
        public virtual System.String ShipAddress
        {
            get => _entity.ShipAddress;
            set => _entity.ShipAddress = value;
        }

        /// <summary>
        /// Gets or sets value from column [ShipCity].
        /// </summary>
        public virtual System.String ShipCity
        {
            get => _entity.ShipCity;
            set => _entity.ShipCity = value;
        }

        /// <summary>
        /// Gets or sets value from column [ShipRegion].
        /// </summary>
        public virtual System.String ShipRegion
        {
            get => _entity.ShipRegion;
            set => _entity.ShipRegion = value;
        }

        /// <summary>
        /// Gets or sets value from column [ShipPostalCode].
        /// </summary>
        public virtual System.String ShipPostalCode
        {
            get => _entity.ShipPostalCode;
            set => _entity.ShipPostalCode = value;
        }

        /// <summary>
        /// Gets or sets value from column [ShipCountry].
        /// </summary>
        public virtual System.String ShipCountry
        {
            get => _entity.ShipCountry;
            set => _entity.ShipCountry = value;
        }
    }
}

// ReSharper disable once IdentifierTypo
namespace Contoso.Unicorn.GraphQL.Proxies
{
    /// <summary>
    /// Definition of table order detail.
    /// </summary>
    [SuppressMessage("ReSharper", "UnusedMember.Global")]
    [SuppressMessage("ReSharper", "MemberHidesStaticFromOuterClass")]
    [SuppressMessage("ReSharper", "InconsistentNaming")]
    [SuppressMessage("ReSharper", "PartialTypeWithSinglePart")]
    [GeneratedCode("TextTemplatingFileGenerator", "1.0.0")]
    public partial class OrderDetailProxy : BaseProxy
    {
        private readonly OrderDetailEntity _entity;

        /// <inheritdoc />
        public OrderDetailProxy(OrderDetailEntity entity) : base(entity) => _entity = entity;

        /// <summary>
        /// Gets or sets value from column [OrderId].
        /// </summary>
        public virtual System.String OrderId
        {
            get => _entity.OrderId;
            set => _entity.OrderId = value;
        }

        /// <summary>
        /// Gets or sets value from column [ProductId].
        /// </summary>
        public virtual System.String ProductId
        {
            get => _entity.ProductId;
            set => _entity.ProductId = value;
        }

        /// <summary>
        /// Gets or sets value from column [UnitPrice].
        /// </summary>
        public virtual System.Decimal UnitPrice
        {
            get => _entity.UnitPrice;
            set => _entity.UnitPrice = value;
        }

        /// <summary>
        /// Gets or sets value from column [Quality].
        /// </summary>
        public virtual System.Int16 Quality
        {
            get => _entity.Quality;
            set => _entity.Quality = value;
        }

        /// <summary>
        /// Gets or sets value from column [Discount].
        /// </summary>
        public virtual System.Decimal Discount
        {
            get => _entity.Discount;
            set => _entity.Discount = value;
        }
    }
}

// ReSharper disable once IdentifierTypo
namespace Contoso.Unicorn.GraphQL.Proxies
{
    /// <summary>
    /// Definition of table product.
    /// </summary>
    [SuppressMessage("ReSharper", "UnusedMember.Global")]
    [SuppressMessage("ReSharper", "MemberHidesStaticFromOuterClass")]
    [SuppressMessage("ReSharper", "InconsistentNaming")]
    [SuppressMessage("ReSharper", "PartialTypeWithSinglePart")]
    [GeneratedCode("TextTemplatingFileGenerator", "1.0.0")]
    public partial class ProductProxy : BaseProxy
    {
        private readonly ProductEntity _entity;

        /// <inheritdoc />
        public ProductProxy(ProductEntity entity) : base(entity) => _entity = entity;

        /// <summary>
        /// Gets or sets value from column [ProductName].
        /// </summary>
        public virtual System.String ProductName
        {
            get => _entity.ProductName;
            set => _entity.ProductName = value;
        }

        /// <summary>
        /// Gets or sets value from column [SupplierId].
        /// </summary>
        public virtual System.String SupplierId
        {
            get => _entity.SupplierId;
            set => _entity.SupplierId = value;
        }

        /// <summary>
        /// Gets or sets value from column [CategoryId].
        /// </summary>
        public virtual System.String CategoryId
        {
            get => _entity.CategoryId;
            set => _entity.CategoryId = value;
        }

        /// <summary>
        /// Gets or sets value from column [UnitPrice].
        /// </summary>
        public virtual System.Decimal UnitPrice
        {
            get => _entity.UnitPrice;
            set => _entity.UnitPrice = value;
        }

        /// <summary>
        /// Gets or sets value from column [IsDiscontinued].
        /// </summary>
        public virtual System.Boolean IsDiscontinued
        {
            get => _entity.IsDiscontinued;
            set => _entity.IsDiscontinued = value;
        }
    }
}

// ReSharper disable once IdentifierTypo
namespace Contoso.Unicorn.GraphQL.Proxies
{
    /// <summary>
    /// Definition of table shipper.
    /// </summary>
    [SuppressMessage("ReSharper", "UnusedMember.Global")]
    [SuppressMessage("ReSharper", "MemberHidesStaticFromOuterClass")]
    [SuppressMessage("ReSharper", "InconsistentNaming")]
    [SuppressMessage("ReSharper", "PartialTypeWithSinglePart")]
    [GeneratedCode("TextTemplatingFileGenerator", "1.0.0")]
    public partial class ShipperProxy : BaseProxy
    {
        private readonly ShipperEntity _entity;

        /// <inheritdoc />
        public ShipperProxy(ShipperEntity entity) : base(entity) => _entity = entity;

        /// <summary>
        /// Gets or sets value from column [CompanyName].
        /// </summary>
        public virtual System.String CompanyName
        {
            get => _entity.CompanyName;
            set => _entity.CompanyName = value;
        }

        /// <summary>
        /// Gets or sets value from column [Phone].
        /// </summary>
        public virtual System.String Phone
        {
            get => _entity.Phone;
            set => _entity.Phone = value;
        }
    }
}

// ReSharper disable once IdentifierTypo
namespace Contoso.Unicorn.GraphQL.Proxies
{
    /// <summary>
    /// Definition of table supplier.
    /// </summary>
    [SuppressMessage("ReSharper", "UnusedMember.Global")]
    [SuppressMessage("ReSharper", "MemberHidesStaticFromOuterClass")]
    [SuppressMessage("ReSharper", "InconsistentNaming")]
    [SuppressMessage("ReSharper", "PartialTypeWithSinglePart")]
    [GeneratedCode("TextTemplatingFileGenerator", "1.0.0")]
    public partial class SupplierProxy : BaseProxy
    {
        private readonly SupplierEntity _entity;

        /// <inheritdoc />
        public SupplierProxy(SupplierEntity entity) : base(entity) => _entity = entity;

        /// <summary>
        /// Gets or sets value from column [CompanyName].
        /// </summary>
        public virtual System.String CompanyName
        {
            get => _entity.CompanyName;
            set => _entity.CompanyName = value;
        }

        /// <summary>
        /// Gets or sets value from column [ContactName].
        /// </summary>
        public virtual System.String ContactName
        {
            get => _entity.ContactName;
            set => _entity.ContactName = value;
        }

        /// <summary>
        /// Gets or sets value from column [ContactTitle].
        /// </summary>
        public virtual System.String ContactTitle
        {
            get => _entity.ContactTitle;
            set => _entity.ContactTitle = value;
        }

        /// <summary>
        /// Gets or sets value from column [Address].
        /// </summary>
        public virtual System.String Address
        {
            get => _entity.Address;
            set => _entity.Address = value;
        }

        /// <summary>
        /// Gets or sets value from column [City].
        /// </summary>
        public virtual System.String City
        {
            get => _entity.City;
            set => _entity.City = value;
        }

        /// <summary>
        /// Gets or sets value from column [Region].
        /// </summary>
        public virtual System.String Region
        {
            get => _entity.Region;
            set => _entity.Region = value;
        }

        /// <summary>
        /// Gets or sets value from column [PostalCode].
        /// </summary>
        public virtual System.String PostalCode
        {
            get => _entity.PostalCode;
            set => _entity.PostalCode = value;
        }

        /// <summary>
        /// Gets or sets value from column [Country].
        /// </summary>
        public virtual System.String Country
        {
            get => _entity.Country;
            set => _entity.Country = value;
        }

        /// <summary>
        /// Gets or sets value from column [Phone].
        /// </summary>
        public virtual System.String Phone
        {
            get => _entity.Phone;
            set => _entity.Phone = value;
        }

        /// <summary>
        /// Gets or sets value from column [Fax].
        /// </summary>
        public virtual System.String Fax
        {
            get => _entity.Fax;
            set => _entity.Fax = value;
        }
    }
}
